apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/kube-default: true
    app: jenkins
    component: agent
spec:
  containers:
  - name: terragrunt-azure
    image: devopsinfra/docker-terragrunt:azure-tf-1.1.4-tg-0.35.20
    command:
    - sleep
    args:
    - 99d
  nodeSelector:
    jenkins: worker
  tolerations:
  - key: jenkins
    operator: Equal
    value: worker
    effect: NoSchedule
