on:
  workflow_dispatch:
    inputs:
      ReleaseLabelVersion:
        type: string
        description: The Label version of the POD
        default: '8.1.0.0'
        required: true
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: sleep 1m; echo "welcome to the repository!"
        shell: bash
